# Generated by Django 4.2.7 on 2023-12-07 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of exercise', max_length=100)),
                ('body_part', models.CharField(choices=[], help_text='body part for exercise', max_length=30)),
                ('public', models.BooleanField(default=False, help_text='defines if exercise is visible for other users')),
                ('user', models.ForeignKey(blank=True, default=None, help_text='exercise owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrainingPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='training plan name', max_length=100)),
                ('last_training', models.DateTimeField(blank=True, help_text='date of last training', null=True)),
                ('exercises', models.ManyToManyField(help_text='exercises assigned to this plan', to='trainings.exercise')),
                ('user', models.ForeignKey(help_text='training plan owner', on_delete=django.db.models.deletion.CASCADE, related_name='user_training_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
