# Generated by Django 4.2.7 on 2023-12-07 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_exercise_usertrainingplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='training record category', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='training start time')),
                ('end_time', models.DateTimeField(help_text='training end time')),
                ('training_duration', models.DurationField(help_text='training duration')),
                ('note', models.TextField(blank=True, default=None, help_text='optional training note', null=True)),
                ('training_plan', models.ForeignKey(help_text='training plan', on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='trainings.usertrainingplans')),
                ('user', models.ForeignKey(help_text='training owner', on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
