# Generated by Django 4.2.7 on 2023-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_trainingrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='body_part',
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.ManyToManyField(help_text='body part for exercise', to='trainings.bodypart'),
        ),
    ]
