# Generated by Django 5.0.1 on 2024-01-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_trainingplanexerciseinfo_trainingexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrainingplans',
            name='exercises',
            field=models.ManyToManyField(blank=True, help_text='exercises assigned to this plan', null=True, to='trainings.exercise'),
        ),
    ]
