# Generated by Django 5.0.1 on 2024-01-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_alter_usertrainingplans_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='exercise',
            field=models.ForeignKey(default=None, help_text='record exercise', on_delete=django.db.models.deletion.CASCADE, related_name='training_exercise', to='trainings.exercise'),
        ),
        migrations.AlterField(
            model_name='usertrainingplans',
            name='exercises',
            field=models.ManyToManyField(blank=True, default=None, help_text='exercises assigned to this plan', to='trainings.exercise'),
        ),
        migrations.AlterField(
            model_name='usertrainingplans',
            name='exercises_info',
            field=models.ManyToManyField(blank=True, to='trainings.trainingplanexerciseinfo'),
        ),
    ]
