# Generated by Django 5.0.2 on 2024-08-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_trainingexercise_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrainingplans',
            name='exercises',
        ),
        migrations.AlterField(
            model_name='trainingplanexerciseinfo',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_id', to='trainings.exercise'),
        ),
    ]
