# Generated by Django 5.0.2 on 2024-09-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_remove_usertrainingplans_exercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplanexerciseinfo',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_info', to='trainings.exercise'),
        ),
        migrations.AlterField(
            model_name='usertrainingplans',
            name='exercises_info',
            field=models.ManyToManyField(blank=True, related_name='training_plans', to='trainings.trainingplanexerciseinfo'),
        ),
    ]
