# Generated by Django 5.0.2 on 2024-09-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_alter_trainingplanexerciseinfo_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplanexerciseinfo',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='order of the exercise in the training plan'),
        ),
    ]
