# Generated by Django 5.0.2 on 2024-09-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_trainingplanexerciseinfo_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplanexerciseinfo',
            name='ordering',
        ),
    ]
